language: node_js
node_js:
  - node
  - 6
  - 8
sudo: false
matrix:
  allow_failures:
    - node_js: node
script:
  - npm test
  - npm run test-browser
after_script:
  - npm run coverage
  - cat coverage/karma/*/lcov.info coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js > /dev/null 2>&1
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
