language: node_js
node_js:
  - node
  - 4
  - 6
sudo: false
matrix:
  allow_failures:
    - nodejs: node
script:
  - make test-cov
  - make test-browser
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
